### ISSUE TITLE
各種IDの仕様について

### ISSUE THREAD

**Issue by kenken714** [traP-jp/traO-Judge#37]
IDの仕様について、改めて考えましたが、不完全なところがあると思うので意見が欲しいです

結論から言うと、primary keyは全てUUIDで持ち、userID, problemID については連番のIDも持ちたいと考えています
また、 contestIDについては連番のIDか、コンテスト名の短いエイリアスを持ちたいです

前提として、IDは userID, problemID, submissionID, testcaseID, (contestID) を考えます
## 連番が不利な点
- IDが容易に推定しうる・一部トランザクション処理が必要
- traOJudgeは多様な問題・コンテストが想定されるため、連番に対するクエリ・ロジックに依存するべきではない

## 連番が有利な点
- URLが短くなる
- IDが容易に推定できる & 短いことにより、APIを使った操作が容易になる
    - 例えば、OJ(競プロ支援ツール)を用いてコンテストに提出するときに、コンテストIDや問題番号で指定できる

まず、連番に対するクエリはしないようにします。
連番に対するクエリのユースケースとして、「virtual contestに対して関連する連番の問題を追加する」というケースがありますが、これはコンテストを検索してまとめて追加する機能を実装することでカバーできます
「OJを用いてコンテストの問題を提出する」ケースでは、コンテスト名のエイリアス + コンテスト内での問題ID(連番) を定め、UUIDと結びつけることで実現できます

その上で、「URLを短くする」ためにuserID, problemIDを連番を振りたいと思っています。primary keyはUUIDにして、APIにアクセスするときは連番のIDにしたいと思っています

**Comment by mathsuky** [comment]
返信遅れて申し訳ないです:pray:
一点質問なのですが，submissionIDには連番を振らないということですか？
おそらく，URLが短いことが嬉しく思える瞬間の一つとしてユーザー間で問題や回答を共有するときを想定していると思っていて，そしてsubmissionについてはその機会が多そうであると思ったからです。

**Comment by kenken714** [comment]
返信ありがとうございます！
> おそらく，URLが短いことが嬉しく思える瞬間の一つとしてユーザー間で問題や回答を共有するときを想定していると思っていて，そしてsubmissionについてはその機会が多そうであると思ったからです。

おっしゃる通りで、submissionIDにも連番を振るべきです:pray:

**Comment by mathsuky** [comment]
遅れてごめんなさい:pray:
ありがとうございます！そうであればやり方自体に問題はないと思います。
個人的には，やや有利な点の嬉しさが少ないのかなとは思っているのですが，連番にすること自体に反対ではないです。
@PonponJuice  くん， @ramdos0207 くん  の意見も聞きたいです。

**Comment by kenken714** [comment]
このIDの仕様で確定したいと思います
