### ISSUE TITLE
DB scheme の timeの接尾辞の不一致を修正

### ISSUE THREAD

**Issue by kenken714** [traP-jp/traO-Judge#58]
- `publish_time` -> `created_at`
- `updated_time` -> `updated_at`
など

**Comment by PonponJuice** [comment]
pubulishはcreatedの方が良さげ

**Comment by kenken714** [comment]
> pubulishはcreatedの方が良さげ

@PonponJuice これ進んでる...？やってなかったら一旦僕が回収する

**Comment by kenken714** [comment]
あれ、ponがassignされてるわけじゃなかったか

**Comment by PonponJuice** [comment]
まだ、やってないのでやるんだったらやってもいいよ

**Comment by PonponJuice** [comment]
嘘、今からやります
